DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS drinks CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS drinkprices;
DROP TABLE IF EXISTS indivscores;
